# -*- coding: utf-8 -*-
"""aula3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MCxcD8JAdZTGBQ-5hIByHfAr9MejvLsA
"""

# UNINASSAU PAULISTA
# DOCENTE: PROF. CLOVES ROCHA
# ESTUDANTE: ASLLEY EMANUEL
# DISCIPLINA: LÓGICA DE PROGRAMAÇÃO

A = 10
B = 20
C = (A+B)
print(C)

#Exemplo 1 - atribuição de média
a = 10
b = 3
soma = a + b
media = (a + b) / 2
print('soma:' , soma)
print('Média:' , media)

# Exemplo 2 - usando módulo e exponenciação:

n = 7
resto = n % 2
quad = n ** 2
print('Resto da divisão por 2:' , resto)
print('Quadrado' , quad)