# -*- coding: utf-8 -*-
"""aula3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VAkrDlidEokUsgvfNeBpKvNk5oKTwoYz
"""

# UNINASSSAU PAULISTA
# DOCENTE: PROF. CLOVES ROCHA
# ESTUDANTE: ...
# DISCIPLINA: LÓGICA DE PROGRAMAÇÃO

A = 10
B = 20
C = (A+B)
print(C)

# Exemplo 1 — atribuição e operação:
a = 10
b = 12
soma = a + b
media = (a + b) / 2
print('Soma:' , soma)
print('Média:' , media)

# Exemplo 2 — usando módulo e exponenciação:

n = 7
resto = n % 2
quad = n ** 2
print('Resto da divisão por 2:' , resto)
print('Quadrado:' , quad)

a = int(input("Digite o primeiro número: "))
b = int(input("Digite o segundo número: "))
op = input("Operador (+, -, *, /, %): ")

if op == "+":
 resultado = a + b
elif op == "-":
 resultado = a - b
elif op == "*":
 resultado = a * b
elif op == "/":
 if b != 0:
  resultado = a / b
 else:
  resultado = None
 print("Erro: divisão por zero.")
elif op == "%":
 if b != 0:
  resultado = a % b
 else:
  resultado = None
 print("Erro: divisão por zero.")
else:
 resultado = None
 print("Operador inválido.")

if resultado is not None:
 print(f"Resultado: {resultado}")